### ISSUE TITLE
Licencia original y de la traducción

### ISSUE THREAD

**Issue by mauriciopasquier** [edsl/articulos#18]
Hay que agregar un campo para cada una, según #10

**Comment by fauno** [comment]
dijimos poner un array yaml

```
original:
  author:
  license:
translation:
  author:
  license:
```
